version: '3.8'

services:
  golang:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    image: news-service:latest
    container_name: news-service
    command: ["serve-http"]
    ports:
      - "8080:3000" #sesuaikan .env dengan port yang diinginkan
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
      - elasticsearch

  migrate:
    image: news-service:latest
    command: ["migrate-db"]
    depends_on:
      - postgres
    networks:
      - app-network

  worker:
    image: news-service:latest
    command: ["start-worker"]
    depends_on:
      - redis
    networks:
      - app-network

  test:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    command: ["go", "test", "-v", "./..."]
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=adhika #sesuaikan jika ingin menggunakan username
      - POSTGRES_PASSWORD=adhika #sesuaikan jika ingin menggunakan password
      - POSTGRES_DB=news_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  elasticsearch-data:

networks:
  app-network:
    driver: bridge
